name: Hello World Workflow

on:
  push:
    branches:
      - main
      - dev

jobs:
  say-hello:
    runs-on: self-hosted
    steps:
    - name: Print Hello World
      shell: cmd
      run: echo "Hello World!!!"
