name: Python Testing Workflow

on:
  push:
    branches:
      - main
      - dev

jobs:
  test-python:
    runs-on: self-hosted
    steps:
      - name: Install pytest
        run: pip install pytest

      - name: Run Pytest
        run: pytest C:\Users\louisli\Desktop\githubAction\githubAction_test\test_script.py