name: Python Testing Workflow

on:
  push:
    branches:
      - main
      - dev

jobs:
  test-python:
    runs-on: self-hosted
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Replace with the version you need

      - name: Install pytest
        run: pip install pytest

      - name: Run Pytest
        run: pytest C:\Users\louisli\Desktop\githubAction\githubAction_test\test_script.py