name: Python Testing Workflow

on:
  push:
    branches:
      - main
      - dev

jobs:
  test-python:
    runs-on: self-hosted
    steps:
      - name: Print PATH
        shell: cmd
        run: echo %PATH%
      - name: Run Pytest
        shell: cmd
        run: pytest test_script.py