name: Pytest Workflow for Branches

on:
  push:
    branches:
      - main
      - dev

jobs:
  pytest-on-main:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your specific Python version if needed
      - name: Install pytest
        run: pip install pytest
      - name: Run pytest on main branch
        run: pytest test_script.py

  pytest-on-dev:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your specific Python version if needed
      - name: Install pytest
        run: pip install pytest
      - name: Run pytest on dev branch
        run: pytest test_script.py