name: Python Testing Workflow

on:
  push:
    branches:
      - main
      - dev

jobs:
  test-python:
    runs-on: self-hosted
    steps:
      - name: Add Python to PATH
        run: |
          echo 'C:\Users\louisli\AppData\Local\Programs\Python\Python311' >> $Env:PATH
        shell: cmd

      - name: Install pytest
        run: |
          C:\Users\louisli\AppData\Local\Programs\Python\Python311\python.exe -m pip install pytest
        shell: cmd

      - name: Run Pytest
        run: |
          C:\Users\louisli\AppData\Local\Programs\Python\Python311\python.exe -m pytest C:\Users\louisli\Desktop\githubAction\githubAction_test\test_script.py
        shell: cmd